name: Windows-CRD

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Enter CRD code'
        required: true
      pincode:
        description: 'Six digit Pinn'
        required: true
  
jobs:
  build:
    name: Start Building...
    runs-on: windows-latest


    steps:

      - name: Downloading & Installing Essentials

        run: |

          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/qdyd4p9t6xoabl95n5o3g/Downloads.bat?rlkey=snr74vv1vr8k5suujugvrhjtm&dl=1" -OutFile "Downloads.bat"

          cmd /c Downloads.bat



      - name: Log In To AnyDesk

        run: cmd /c show.bat


     steps:

- name: Download

  run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip

- name: Extract

  run: Expand-Archive ngrok.zip

- name: Auth

  run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

  env:

    NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

- name: Enable TS

  run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0

- run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

- run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

- run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

- name: Create Tunnel

  run: .\ngrok\ngrok.exe tcp 3389

    steps:
    - uses: actions/checkout@v2
    - name: Initializing Setup
      run: ./setup.ps1
    - name: Starting CRD
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
    - name: Keep Alive
      run: ./timeout.ps1
