name: Windows-CRD

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Enter CRD code'
        required: true
      pincode:
        description: 'Six digit Pinn'
        required: true
  
jobs:
  build:
    runs-on: windows-lates
    
steps:
  - uses: actions/checkout@v2

       run:|

        Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/qdyd4p9t6xoabl95n5o3g/Downloads.bat?rlkey=snr74vv1vr8k5suujugvrhjtm&dl=1" -OutFile "Downloads.bat"

          cmd /c Downloads.bat
          
    -name: Log In To AnyDesk

      run:cmd /c show.bat
   
      run:./setup.ps1
      run:${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
      run:./timeout.ps1

